version: '3.7'
services:
    web:
        build: .
        image: teknofage/camelot-fortune:1.0
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        environment:
            - FLASK_ENV=development
        build: .
        # The thing that changes the most often
        command: flask run --host=0.0.0.0
        



